services:
  product-service:
    build:
      context: .
      dockerfile: Module.Products.Server/Dockerfile
    ports:
      - "8001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal;Database=productsdb;User Id=sa;Password=NRoa9625@;Encrypt=false;TrustServerCertificate=True;